### ISSUE TITLE
Description in books query for openlibrary returns [object Object]

### ISSUE THREAD

**Issue by oae** [oae/openapi#28]
![image](https://app.gitkraken.com/api/glo/boards/5bcf5cffe0c0c40e000abb92/attachments/5bdb419a1fc3b8000f7bcfdf)

**Comment by halitogunc** [comment]
Some of the books have a good description like Harry Potter.
![image](https://user-images.githubusercontent.com/13641726/47948948-47815680-df4b-11e8-9fd0-0c7e8af480c9.png) 

But most of them do not have a clear description which comes from publisher. Also some of them don't have any description. In my opinion, we have 2 options in here;

 - We can suspend description field for now
 - OR We can use temporary solution like ```description: resolveAlias('description.value')```

 If you have any other suggestion please check out;
 PR : [/pull/31]
